CREATE TABLE products (
	id BIGSERIAL PRIMARY KEY,
	category_id BIGINT,
	name VARCHAR(255) NOT NULL,
	slug VARCHAR(255) NOT NULL UNIQUE,
	description TEXT NOT NULL DEFAULT '',
	price_cents BIGINT NOT NULL,
	stock INTEGER NOT NULL DEFAULT 0,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	main_image VARCHAR(255) NOT NULL DEFAULT '',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_products_category_id ON products (category_id);
