CREATE TABLE sessions (
	id BIGSERIAL PRIMARY KEY,
	token VARCHAR(64) NOT NULL UNIQUE,
	user_id BIGINT NOT NULL,
	expires_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sessions_user_id ON sessions (user_id);
