CREATE TABLE addresses (
	id BIGSERIAL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	recipient VARCHAR(255) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	province VARCHAR(64) NOT NULL DEFAULT '',
	city VARCHAR(64) NOT NULL DEFAULT '',
	district VARCHAR(64) NOT NULL DEFAULT '',
	street VARCHAR(255) NOT NULL DEFAULT '',
	is_default BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_addresses_user_id ON addresses (user_id);
