CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	phone VARCHAR(20) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL DEFAULT '',
	display_name VARCHAR(255) NOT NULL DEFAULT '',
	status VARCHAR(20) NOT NULL DEFAULT 'active',
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
