CREATE TABLE coupons (
	id BIGSERIAL PRIMARY KEY,
	code VARCHAR(32) NOT NULL UNIQUE,
	type VARCHAR(20) NOT NULL,
	value_cents BIGINT NOT NULL DEFAULT 0,
	percent_off INTEGER NOT NULL DEFAULT 0,
	threshold_cents BIGINT NOT NULL DEFAULT 0,
	total_count INTEGER NOT NULL DEFAULT 0,
	starts_at TIMESTAMP,
	expires_at TIMESTAMP,
	enabled BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
